name: Build bitcoind on push, or PR to master

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    name: Build Bitcoind
    runs-on: ubuntu-18.04

    env:
      QEMU_VERSION: v4.2.0
      DOCKER_BUILDKIT: 1

    strategy:
      fail-fast: false
      matrix:
        subver:
#          - 0.16
#          - 0.17
          - 0.18
#          - 0.19

        arch:
          - amd64
          - arm64v8
          - arm32v7

    steps:
      - uses: actions/checkout@v2.0.0

      # NOTE: trims `v8` suffix from `arm64v8`
      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        env:
          ARCH: ${{ matrix.arch }}
        run: docker run --rm --privileged meedamian/simple-qemu:$QEMU_VERSION-${ARCH%v8} -p yes

      - name: Build Bitcoind
        run: >
          docker build "${{ matrix.subver }}/"
          --build-arg="ARCH=${{ matrix.arch }}"
          --tag=bitcoind

      - name: Print versions, and make sure binaries are runnable
        run: |
          docker run --rm  --entrypoint=uname   bitcoind  -a

          docker run --rm  bitcoind  --version

          docker run --rm  --entrypoint=bitcoin-cli  bitcoind  --version
          docker run --rm  --entrypoint=bitcoin-tx   bitcoind  --help

          MINOR="${{ matrix.subver }}"
          if [ "${MINOR#0.}" -lt "18" ]; then
            exit 0
          fi

          docker run --rm bitcoin-wallet --help
