name: Build bitcoind on push, or PR to master

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    name: Build Bitcoind
    runs-on: ubuntu-18.04

    env:
      APP: bitcoind
      QEMU_VERSION: v4.2.0
      DOCKER_BUILDKIT: 1

    strategy:
      fail-fast: false
      matrix:
        subver:
          - 0.16
          - 0.17
          - 0.18
          - 0.19

        arch:
          - amd64
          - arm32v7
          - arm64v8

    steps:
      - uses: actions/checkout@v2

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: docker run --rm --privileged "meedamian/simple-qemu:$QEMU_VERSION-${{ matrix.arch }}" -p yes

      - name: Build ${{ env.APP }}
        run: >
          docker build "${{ matrix.subver }}/"
          --build-arg "ARCH=${{ matrix.arch }}"
          --tag       "$APP"

      - name: Make sure binaries can be run
        env:
          MINOR: ${{ matrix.subver }}
        run: |
          run() {
            ENTRYPOINT="${1:-$APP}"; shift
            ARGS=${*:-"--version"}

            printf "\n$ %s %s\n"  "$ENTRYPOINT"  "$ARGS"
            docker run --rm  --entrypoint "$ENTRYPOINT"  "$APP"  $ARGS
          }

          run  uname -a
          run  bitcoind
          run  bitcoin-cli
          run  bitcoin-tx --help | head -n 1

          # If version higher, or equal than v0.18.0, also run `bitcoin-wallet` binary
          if [ "${MINOR#0.}" -ge "18" ]; then
            run  bitcoin-wallet --help | head -n 1
          fi
