name: Build bitcoind on push, or PR to master

env:
  APP: bitcoind

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    name: Build bitcoind
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        subver:
          - '0.16'
          - '0.17'
          - '0.18'
          - '0.19'
          - '0.20'
          - '0.21'
          - '22.0'
          - '23.0'
          - '24.0'
          - '25.0'

        arch:
          - amd64
          - arm32v7
          - arm64v8

    env:
      QEMU_VERSION: v5.0.0
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: docker run --rm --privileged "meedamian/simple-qemu:$QEMU_VERSION-${{ matrix.arch }}" -p yes

      - name: Build ${{ env.APP }}
        run: >
          docker build "${{ matrix.subver }}/"
          --build-arg "ARCH=${{ matrix.arch }}"
          --tag       "$APP"

      - name: Show built image details
        run: docker images "$APP"

      - name: Run sanity checks
        env:
          DIR: /usr/local/bin
          MINOR: ${{ matrix.subver }}
        run: |
          run() {
            ENTRYPOINT="${1:-$APP}"; shift
            ARGS=${*:-"--version"}

            printf "\n$ %s %s\n"  "$ENTRYPOINT"  "$ARGS"
            docker run --rm  --entrypoint "$ENTRYPOINT"  "$APP"  $ARGS
          }

          docker inspect "$APP" | jq '.'
          printf "\n"

          run bitcoind | head -n 1
          run bitcoin-cli
          run bitcoin-tx --help | head -n 1

          # If version higher, or equal than v0.18.0, also run `bitcoin-wallet` binary
          if [ "${MINOR#0.}" -ge "18" ]; then
            run bitcoin-wallet --help | head -n 1
          fi

          run uname -a
          run cat /etc/os-release
          run sha256sum "$DIR/bitcoind" "$DIR/bitcoin-cli"
